Targeting: Target Class Reference
Target Class Reference
A class that represents a single 2012 'Rebound Rumble' rectangular target.
#include <Target.h>
Public Member Functions
Target ()
Constructs an empty Target object.
Target (CvSeq *cntr)
Creates a target from a CvSeq contour.
CvPoint getBoundingBoxPoint1 ()
Returns the upper left point of the bounding box.
CvPoint getBoundingBoxPoint2 ()
Returns the bottom right point of the bounding box.
CvPoint getCenter ()
Gets the center point of the target.
void calculateHoopPosition (int numPointsPerSide, int crossProductThreshold, aruco::CameraParameters camParams)
Calculates the position of the hoop relative to the camera.
aruco::Marker getMarker ()
Returns the Aruco marker representing the target.
void drawTarget (IplImage *img, CvScalar color)
Draws the target on an image.
void getNavInfo ()
Public Attributes
float offsets [4]
The X, Y, and Z offsets of the target from the camera.
CvSeq contour
The CvSeq contour of the target.
aruco::Marker marker
The Aruco Marker object defining the square portion of the target coplanar with the target and aligned with the target's left edge.
double modelViewMatrix [16]
The OpenGL model view matrix of the target, in a 3x3 rotation matrix appended to a 3x1 translation matrix.
Private Member Functions
void mergeColinearLines ()
Merges all colinear line segments into a single segment; one for each edge of the target.
void spacePointsEvenly (int numPointsPerSide)
A function to space a list of points from a contour in even intervals around the contour.
void calculateSegmentsFromPoints (int crossProductThreshold)
Makes the set of segments on a target from points.
void calculateIntersectionsOfLines ()
Calculates all the intersections of the edges of the target.
void calculateVanishingPoints ()
Calculates vanishing pints from the segments contained in lineSet.
void calculateCornersFromVanishingPoints ()
Intersects vanishing ponts to get the four corners of the target.
void calculateSquare ()
Calculates the corners of the square Marker object. Performs two dicing operations on the four corner points to create an Aruco Marker object, square, centered on the left edge of the target.
void calculatePosition (aruco::CameraParameters camParams)
Calculates the position of the target's hoop from the Aruco marker object.
Private Attributes
CvRect boundingBox
The CvRect defining the bounding box of the target.
CvPoint pointSet [500]
An array of CvPoints defining the points on the target's contour.
int numPoints
The number of poins on the tart's contour.
Line lineSet [500]
An array of Line objects containing the segments between tetarget's points, and, later, the edges of the target.
int numLines
The number of Line objects contained in lineSet.
CvPoint2D32f intersectionSet [1000]
The set of floating-point CvPoints defining the intersection of the edges of the target.
int numIntersections
The number of intersections between the target's edges.
int intersectionLineIndices [2][1000]
An array that indicates which lines formed each intersection points. The first column contains the first line that formed the given intersection point,the second column the second line, and each row is used for a single intersection point.
CvPoint2D32f vPointArray [2]
An array of CvPoint2D32f's defining the two vanishing points of the target's parallel lines.
Line vLines [4]
An array of Line objects, two per vanishing point- one for each line that creaed that vanishing point via intersection.
CvPoint2D32f cornerArray [4]
The four corners of the target, in CvPoint2D32f format.
float hoopCoordinatesArray [16]
Detailed Description
A class that represents a single 2012 'Rebound Rumble' rectangular target.
Author:
Nick Royer
Definition at line 22 of file Target.h.
Constructor & Destructor Documentation
Target::Target ()
Constructs an empty Target object.
Constructs a new Target object with a null contour pointer.
Target::Target (CvSeq * cntr)
Creates a target from a CvSeq contour.
Constructs a new Target objec using the given pointer to a contour. Ideally, the contour should belong to an actual target. This method assumes the given contour is correct; no filtering methods are performed.
Parameters:
cntr The contour that the target will represent.
Member Function Documentation
void Target::calculateCornersFromVanishingPoints () [private]
Intersects vanishing ponts to get the four corners of the target.
See also:
vPointArray
void Target::calculateHoopPosition (int numPointsPerSide, int crossProductThreshold, aruco::CameraParameters camParams)
Calculates the position of the hoop relative to the camera.
Calculates the position, in inches, of the target's hoop center and stores it in an array of X,Y,Z and vector offsets.
Parameters:
numPointsPerSide The number of points desired on the shortest side of the target's contour when spacing the points evenly.
crossProductThreshold A scalar value used to filter out non-colinear lines from the target's segment array. A very low number will filter few lines. A very high number will filter out most lines.
camParams The Aruco camera parameters used in determining the target's position.
See also:
spacePointsEvenly
calculateSegmentsFromPoints
calculateIntersectionsOfLines
calculateVanishingPoints
calculateCornersFromVanishingPoints
calculateSquare
calculatePosition
Referenced by main().
void Target::calculateIntersectionsOfLines () [private]
Calculates all the intersections of the edges of the target.
See also:
lineSet
intersectionSet
void Target::calculatePosition (aruco::CameraParameters camParams) [private]
Calculates the position of the target's hoop from the Aruco marker object.
Parameters:
camParams The Aruco camera parameters used to determine the target's position.
See also:
marker
offsets
void Target::calculateSegmentsFromPoints (int crossProductThreshold) [private]
Makes the set of segments on a target from points.
Parameters:
crossProductThreshold An integer value defining the threshold for filtering out non-colinear line segments.
See also:
lineSet
void Target::calculateSquare () [private]
Calculates the corners of the square Marker object. Performs two dicing operations on the four corner points to create an Aruco Marker object, square, centered on the left edge of the target.
See also:
marker
vPointArray
void Target::calculateVanishingPoints () [private]
Calculates vanishing pints from the segments contained in lineSet.
See also:
lineSet
void Target::drawTarget (IplImage * img, CvScalar color)
Draws the target on an image.
Draws the target on a provided image, including the target's bounding box, center, axes of rotation, contour, and selected points.
Parameters:
img The pointer to an IplImage that the target is to be drawn on.
color A CvScalar defining the desired color of the target's bounding box, contour, and points. Note that all X,Y,Z values are rendered in their conventional colors.
Referenced by main().
CvPoint Target::getBoundingBoxPoint1 ()
Returns the upper left point of the bounding box.
Returns the upper-left point of the target's bounding box.
Returns:
A CvPoint representing the upper-left point of the target's bounding box.
CvPoint Target::getBoundingBoxPoint2 ()
Returns the bottom right point of the bounding box.
Returns the lower-right point of the target's bounding box.
Returns:
A CvPoint representing the lower-right point.
CvPoint Target::getCenter ()
Gets the center point of the target.
Returns the center of the target's bounding box.
Returns:
A CvPoint at the center o the taget's bounding box.
Referenced by main().
aruco::Marker Target::getMarker ()
Returns the Aruco marker representing the target.
void Target::getNavInfo ()
Referenced by main().
void Target::mergeColinearLines () [private]
Merges all colinear line segments into a single segment; one for each edge of the target.
void Target::spacePointsEvenly (int numPointsPerSide) [private]
A function to space a list of points from a contour in even intervals around the contour.
Parameters:
numPointsPerSide The number of points desired on the shortest side of the contour.
Member Data Documentation
CvRect Target::boundingBox [private]
The CvRect defining the bounding box of the target.
Definition at line 83 of file Target.h.
CvSeq Target::contour
The CvSeq contour of the target.
Definition at line 67 of file Target.h.
CvPoint2D32f Target::cornerArray[4] [private]
The four corners of the target, in CvPoint2D32f format.
Definition at line 100 of file Target.h.
float Target::hoopCoordinatesArray[16] [private]
Definition at line 144 of file Target.h.
int Target::intersectionLineIndices[2][1000] [private]
An array that indicates which lines formed each intersection points. The first column contains the first line that formed the given intersection point,the second column the second line, and each row is used for a single intersection point.
Definition at line 93 of file Target.h.
CvPoint2D32f Target::intersectionSet[1000] [private]
The set of floating-point CvPoints defining the intersection of the edges of the target.
Definition at line 91 of file Target.h.
Line Target::lineSet[500] [private]
An array of Line objects containing the segments between tetarget's points, and, later, the edges of the target.
Definition at line 88 of file Target.h.
aruco::Marker Target::marker
The Aruco Marker object defining the square portion of the target coplanar with the target and aligned with the target's left edge.
Definition at line 68 of file Target.h.
double Target::modelViewMatrix[16]
The OpenGL model view matrix of the target, in a 3x3 rotation matrix appended to a 3x1 translation matrix.
Definition at line 71 of file Target.h.
int Target::numIntersections [private]
The number of intersections between the target's edges.
Definition at line 92 of file Target.h.
int Target::numLines [private]
The number of Line objects contained in lineSet.
Definition at line 89 of file Target.h.
int Target::numPoints [private]
The number of poins on the tart's contour.
Definition at line 86 of file Target.h.
float Target::offsets[4]
The X, Y, and Z offsets of the target from the camera.
Definition at line 66 of file Target.h.
Referenced by main().
CvPoint Target::pointSet[500] [private]
An array of CvPoints defining the points on the target's contour.
Definition at line 85 of file Target.h.
Line Target::vLines[4] [private]
An array of Line objects, two per vanishing point- one for each line that creaed that vanishing point via intersection.
Definition at line 98 of file Target.h.
CvPoint2D32f Target::vPointArray[2] [private]
An array of CvPoint2D32f's defining the two vanishing points of the target's parallel lines.
Definition at line 97 of file Target.h.
The documentation for this class was generated from the following file:
Headers/Target.h