Targeting: Headers/HelperFunctions.h File Reference
Headers/HelperFunctions.h File Reference
#include <opencv/cv.h>
#include <aruco/aruco.h>
#include <opencv/cvaux.h>
Functions
float pointDistance (CvPoint point1, CvPoint point2)
Returns the distance between two points.
char * floatToString (float flt)
Converts a float variable into a string for easier display.
CvFont * getFont (float size)
Returns a basic default font.
float calculateVectorFrom3Offsets (float vecX, float vecY, float vecZ)
Calculates the 3D distance from the origin to a point.
void drawAxis (IplImage *Image, aruco::Marker &m, const aruco::CameraParameters &CP)
Draws the 3D axis indicating the orientation of a Aruco marker object.
float convertMarkerCoordinateToInches (float markerCoordinate)
Converts the dimensions of an Aruco marker (meters) to inches.
void matrixMultiply (float *a, double *b, float *result, int dimension)
Multiplies two square matrices.
float inchesToMeters (int inches)
float rad2deg (float rads)
float deg2rad (float degrees)
Function Documentation
float calculateVectorFrom3Offsets (float vecX, float vecY, float vecZ)
Calculates the 3D distance from the origin to a point.
Parameters:
vecX The X-offset of the point from the origin.
vecY The Y-offset of the point from the origin.
vecZ The Z-offset of the point from the origin.
Returns:
The distance from the origin to the given point, expressed in the same units as the inputs.
float convertMarkerCoordinateToInches (float markerCoordinate)
Converts the dimensions of an Aruco marker (meters) to inches.
Parameters:
markerCoordinate The dimension in meters.
Returns:
The dimension in inches.
Referenced by main().
float deg2rad (float degrees)
void drawAxis (IplImage * Image, aruco::Marker & m, const aruco::CameraParameters & CP)
Draws the 3D axis indicating the orientation of a Aruco marker object.
Parameters:
Image A pointer to the desied image to draw on.
m The Aruco marker object the axis indicates the orientation of.
CP The Aruco camera parameters used to project the axis onto the image.
Referenced by main().
char* floatToString (float flt)
Converts a float variable into a string for easier display.
Converts a float variable into a string for easier display. Note that this function is limited to 30 characters or fewer for the resulting string.
Parameters:
flt The float variable desired to be converted to a string.
Returns:
The float variable expressed as a string.
Referenced by main().
CvFont* getFont (float size)
Returns a basic default font.
Parameters:
size The desired font size, from 0 to 1 to an arbitrary float. 0.5 is used primarily by this code.
Returns:
A pointer to a CvFont object of the desired size.
float inchesToMeters (int inches)
void matrixMultiply (float * a, double * b, float * result, int dimension)
Multiplies two square matrices.
Multiplies to matrices. The matrices are expressed as square arrays of dimensions indicated by the dimension parameter. Due to idiosyncracies of the requirements of this function, the first matrix uses doubles while the rest use floats.
Parameters:
a The first matrix to multiply.
b The second matrix to multiply.
result the resulting multiplied matrix.
dimension The size of each square matrix.
float pointDistance (CvPoint point1, CvPoint point2)
Returns the distance between two points.
Parameters:
point1 The first point used for the calculation.
point2 The second point used for the calculation.
Returns:
the distance, in pixels, between the two points.
float rad2deg (float rads)