Targeting: main.cpp File Reference
main.cpp File Reference
#include <opencv/cv.h>
#include <opencv/highgui.h>
#include "./Headers/Threshold.h"
#include "../Constants.h"
#include "../Headers/Target.h"
#include <sstream>
#include "./Headers/Target.h"
#include <aruco/aruco.h>
Functions
int main ()
Variables
IplImage * frame
A pointer to the currently-evaluated frame.
CvSize frameSize
A CvSize object containing the frame's dimensions.
IplImage * frameThreshed
A pointer to the thresholded (B & W) version of the current frame.
CvCapture * camera = NULL
A pointer to the current capture device.
CameraParameters camParameters
The Aruco camera parameters of the current camera.
CvFont font1
The font used for all drawing on the current frame.
float movingCameraAverageForHighestTarget [OFFSETS_SAMPLESPERREADING][3]
The number of samples taveraged together to provide a moving-camera average for he highest target's position.
float movingCameraRunningSum [3] = {0, 0, 0}
The running sums (X, Y, Z) of the highest target's offsets.
int currentSample = 0
The current sample for the running average.
int highestTargetIndex = 0
The index index in targetSet of the highest target in the view.
CvSeq * contours
A pointer to the CvSeq object containing the current set of contours in the image.
Target targetSet [50]
A set of Target objects containing all valid targets visible in the current view.
int numTargets = 0
The number of valid targets visible in the current view.
Function Documentation
int main ()
Definition at line 30 of file main.cpp.
References Target::calculateHoopPosition(), camera, CAMERA_INDEX, camParameters, contours, convertMarkerCoordinateToInches(), drawAxis(), Target::drawTarget(), FILTER_CONTOURS_POINTSPERCONTOURSIDE, FILTER_POINTS_CROSSPRODUCTTHRESHOLD, Threshold::findContours(), floatToString(), font1, frame, frameSize, frameThreshed, Target::getCenter(), Target::getNavInfo(), highestTargetIndex, movingCameraAverageForHighestTarget, numTargets, Target::offsets, OFFSETS_SAMPLESPERREADING, Threshold::pickTargets(), and Threshold::threshold_findGreen().
Variable Documentation
CvCapture* camera = NULL
A pointer to the current capture device.
Definition at line 14 of file main.cpp.
Referenced by main().
CameraParameters camParameters
The Aruco camera parameters of the current camera.
Definition at line 15 of file main.cpp.
Referenced by main().
CvSeq* contours
A pointer to the CvSeq object containing the current set of contours in the image.
Definition at line 23 of file main.cpp.
Referenced by main().
int currentSample = 0
The current sample for the running average.
See also:
movingCameraAveragForHighestTarget
Definition at line 20 of file main.cpp.
CvFont font1
The font used for all drawing on the current frame.
Definition at line 16 of file main.cpp.
Referenced by main().
IplImage* frame
A pointer to the currently-evaluated frame.
Definition at line 11 of file main.cpp.
Referenced by main().
CvSize frameSize
A CvSize object containing the frame's dimensions.
Definition at line 12 of file main.cpp.
Referenced by main().
IplImage* frameThreshed
A pointer to the thresholded (B & W) version of the current frame.
Definition at line 13 of file main.cpp.
Referenced by main().
int highestTargetIndex = 0
The index index in targetSet of the highest target in the view.
See also:
targetSet
Definition at line 21 of file main.cpp.
Referenced by main().
float movingCameraAverageForHighestTarget[OFFSETS_SAMPLESPERREADING][3]
The number of samples taveraged together to provide a moving-camera average for he highest target's position.
Definition at line 18 of file main.cpp.
Referenced by main().
float movingCameraRunningSum[3] = {0, 0, 0}
The running sums (X, Y, Z) of the highest target's offsets.
Definition at line 19 of file main.cpp.
int numTargets = 0
The number of valid targets visible in the current view.
See also:
targetSet
Definition at line 25 of file main.cpp.
Referenced by main().
Target targetSet[50]
A set of Target objects containing all valid targets visible in the current view.
See also:
Target::Target
Definition at line 24 of file main.cpp.