.TH "Constants.h" 3 "1 Mar 2012" "Version 0.5" "Targeting" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Constants.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <opencv/cv.h>\fP
.br
\fC#include <opencv/highgui.h>\fP
.br
\fC#include <aruco/aruco.h>\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "static int \fBthreshold_hueMin\fP = 34"
.br
.ti -1c
.RI "static int \fBthreshold_hueMax\fP = 79"
.br
.ti -1c
.RI "static int \fBthreshold_satMin\fP = 133"
.br
.ti -1c
.RI "static int \fBthreshold_satMax\fP = 255"
.br
.ti -1c
.RI "static int \fBthreshold_valMin\fP = 63"
.br
.ti -1c
.RI "static int \fBthreshold_valMax\fP = 255"
.br
.ti -1c
.RI "static int \fBbBoxBorderThreshold\fP = 5"
.br
.ti -1c
.RI "static float \fBbBoxPercentFillsThreshold\fP = 0.4"
.br
.ti -1c
.RI "static int \fBfilterContours_minContourArea\fP = 400"
.br
.ti -1c
.RI "static float \fBfilterContours_minBBoxAspectRatio\fP = 0.5"
.br
.ti -1c
.RI "static float \fBfilterContours_maxBBoxAspectRatio\fP = 1.5"
.br
.ti -1c
.RI "static int \fBfilterContours_pointsPerContourSide\fP = 6"
.br
.ti -1c
.RI "static int \fBfilterPoints_crossProductThreshold\fP = 30"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "int \fBbBoxBorderThreshold\fP = 5\fC [static]\fP"
.SS "float \fBbBoxPercentFillsThreshold\fP = 0.4\fC [static]\fP"
.SS "float \fBfilterContours_maxBBoxAspectRatio\fP = 1.5\fC [static]\fP"
.SS "float \fBfilterContours_minBBoxAspectRatio\fP = 0.5\fC [static]\fP"
.SS "int \fBfilterContours_minContourArea\fP = 400\fC [static]\fP"
.SS "int \fBfilterContours_pointsPerContourSide\fP = 6\fC [static]\fP"
.SS "int \fBfilterPoints_crossProductThreshold\fP = 30\fC [static]\fP"
.SS "int \fBthreshold_hueMax\fP = 79\fC [static]\fP"
.SS "int \fBthreshold_hueMin\fP = 34\fC [static]\fP"
.SS "int \fBthreshold_satMax\fP = 255\fC [static]\fP"
.SS "int \fBthreshold_satMin\fP = 133\fC [static]\fP"
.SS "int \fBthreshold_valMax\fP = 255\fC [static]\fP"
.SS "int \fBthreshold_valMin\fP = 63\fC [static]\fP"
.SH "Author"
.PP 
Generated automatically by Doxygen for Targeting from the source code.
