.TH "Headers/DetectMarkers.h" 3 "2 Mar 2012" "Version 0.5" "Targeting" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Headers/DetectMarkers.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <opencv/cv.h>\fP
.br
\fC#include '../Constants.h'\fP
.br
\fC#include <opencv/highgui.h>\fP
.br
\fC#include <aruco/aruco.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBdetectMarkers\fP (IplImage *img, std::vector< std::vector< cv::Point2f > > &MarkerCanditates)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void detectMarkers (IplImage * img, std::vector< std::vector< cv::Point2f > > & MarkerCanditates)"
.SH "Author"
.PP 
Generated automatically by Doxygen for Targeting from the source code.
