.TH "Headers/Line.h" 3 "2 Mar 2012" "Version 0.5" "Targeting" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Headers/Line.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <opencv/cv.h>\fP
.br
\fC#include '../Headers/HelperFunctions.h'\fP
.br
\fC#include <aruco/aruco.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBLine\fP"
.br
.RI "\fIA class representing a line or line segment. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Targeting from the source code.
